name: habithero
description: Habit tracking app with Firebase + Quotes API
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.2
  clipboard: ^0.1.3
  fl_chart: ^0.68.0
  flutter_spinkit: ^5.2.1
  table_calendar: ^3.1.2   # optional
  flutter_staggered_animations: ^1.1.1   # ✅ moved here
  share_plus: ^10.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true