// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_VZSdgghmiXDbzqIxnTyNf_MT_aDAx4',
    appId: '1:59622554217:web:bfa8ac3515fd286b5140f8',
    messagingSenderId: '59622554217',
    projectId: 'habit-tracker-final-23ffc',
    authDomain: 'habit-tracker-final-23ffc.firebaseapp.com',
    storageBucket: 'habit-tracker-final-23ffc.firebasestorage.app',
    measurementId: 'G-SPW05E8643',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ObA37oz3N8awRMzmGbyJZq5lNIGftuM',
    appId: '1:59622554217:android:f2c53028f8bc15fd5140f8',
    messagingSenderId: '59622554217',
    projectId: 'habit-tracker-final-23ffc',
    storageBucket: 'habit-tracker-final-23ffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMp0JJ_oDRxc7j48JerNOwtwPvVM4fBhc',
    appId: '1:59622554217:ios:7b918866dedce8015140f8',
    messagingSenderId: '59622554217',
    projectId: 'habit-tracker-final-23ffc',
    storageBucket: 'habit-tracker-final-23ffc.firebasestorage.app',
    iosBundleId: 'com.example.habithero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMp0JJ_oDRxc7j48JerNOwtwPvVM4fBhc',
    appId: '1:59622554217:ios:7b918866dedce8015140f8',
    messagingSenderId: '59622554217',
    projectId: 'habit-tracker-final-23ffc',
    storageBucket: 'habit-tracker-final-23ffc.firebasestorage.app',
    iosBundleId: 'com.example.habithero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1_VZSdgghmiXDbzqIxnTyNf_MT_aDAx4',
    appId: '1:59622554217:web:a384e3c00e75a0345140f8',
    messagingSenderId: '59622554217',
    projectId: 'habit-tracker-final-23ffc',
    authDomain: 'habit-tracker-final-23ffc.firebaseapp.com',
    storageBucket: 'habit-tracker-final-23ffc.firebasestorage.app',
    measurementId: 'G-C0XB6RM2JV',
  );
}
